# Generated by Django 4.1.3 on 2022-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekuracore", "0007_agent_source_of_truth"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agent",
            name="sekuracore__name_b89a3a_idx",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="preshared_secret",
        ),
        migrations.AddField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[("D", "Disabled"), ("A", "Approved"), ("R", "Rejected")], default="D", max_length=1
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["name", "secret"], name="sekuracore__name_d1b317_idx"),
        ),
    ]
