# Generated by Django 4.1.3 on 2022-11-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekuracore", "0008_remove_agent_sekuracore__name_b89a3a_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="offboarding",
        ),
        migrations.AddField(
            model_name="access",
            name="status",
            field=models.CharField(
                choices=[("D", "Disabled"), ("A", "Active"), ("R", "Revoked")], default="D", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[("O", "Onboarding"), ("A", "Active"), ("D", "Offboarding"), ("R", "Offboarded")],
                default="O",
                max_length=1,
            ),
        ),
    ]
